//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubadora.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direcciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direcciones()
        {
            this.Emprendedores = new HashSet<Emprendedores>();
        }
    
        public string Id { get; set; }
        public string StrCalle { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> IdMunicipio { get; set; }
        public Nullable<int> IdColonia { get; set; }
        public Nullable<int> IntNumeroInterior { get; set; }
        public Nullable<int> IntNumeroExterior { get; set; }
    
        public virtual CatColonias CatColonias { get; set; }
        public virtual CatEstados CatEstados { get; set; }
        public virtual CatMunicipios CatMunicipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emprendedores> Emprendedores { get; set; }
    }
}
