//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubadora.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiantes
    {
        public string Id { get; set; }
        public string StrNombre { get; set; }
        public string StrApellidoPaterno { get; set; }
        public string StrApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string IdTelefono { get; set; }
        public string IdCarrera { get; set; }
        public string IdCatGrupo { get; set; }
        public string StrGrupoDescripcion { get; set; }
        public string IdCatPeriodoEstadia { get; set; }
        public string IdEmprendimientoEstadia { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual CatCarreras CatCarreras { get; set; }
        public virtual CatGrupos CatGrupos { get; set; }
        public virtual CatPeriodoEstadia CatPeriodoEstadia { get; set; }
        public virtual EmprendimientoEstadia EmprendimientoEstadia { get; set; }
        public virtual Telefonos Telefonos { get; set; }
        public virtual Status Status { get; set; }
    }
}
