//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubadora.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyectos()
        {
            this.Colaboradores = new HashSet<Colaboradores>();
            this.RecursosProyectos = new HashSet<RecursosProyectos>();
            this.ServiciosUniversitarios = new HashSet<ServiciosUniversitarios>();
        }
    
        public string Id { get; set; }
        public string StrNombre { get; set; }
        public string StrNombreEmpresa { get; set; }
        public string IdGiro { get; set; }
        public string StrDescripcion { get; set; }
        public string IdFase { get; set; }
        public int IntConstituidaLegal { get; set; }
        public string StrObservaciones { get; set; }
        public string StrRFC { get; set; }
        public System.DateTime DtFechaRegistro { get; set; }
        public string IdEmprendedor { get; set; }
        public Nullable<int> IdStatus { get; set; }
    
        public virtual CatFases CatFases { get; set; }
        public virtual CatGiros CatGiros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Colaboradores> Colaboradores { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecursosProyectos> RecursosProyectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciosUniversitarios> ServiciosUniversitarios { get; set; }
        public virtual SubModuloSesionesProyecto SubModuloSesionesProyecto { get; set; }
        public virtual Emprendedores Emprendedores { get; set; }
    }
}
