//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubadora.Business.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CatalogosEntidades {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogosEntidades() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Incubadora.Business.Recursos.CatalogosEntidades", typeof(CatalogosEntidades).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CatCarreras.
        /// </summary>
        internal static string CatCarreras {
            get {
                return ResourceManager.GetString("CatCarreras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CatGiros.
        /// </summary>
        internal static string CatGiros {
            get {
                return ResourceManager.GetString("CatGiros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CatPeriodoEstadia.
        /// </summary>
        internal static string CatPeriodoEstadia {
            get {
                return ResourceManager.GetString("CatPeriodoEstadia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Colaboradores.
        /// </summary>
        internal static string Colaboradores {
            get {
                return ResourceManager.GetString("Colaboradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emprendedores.
        /// </summary>
        internal static string Emprendedores {
            get {
                return ResourceManager.GetString("Emprendedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string Proyectos {
            get {
                return ResourceManager.GetString("Proyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RecursosProyectos.
        /// </summary>
        internal static string RecursosProyectos {
            get {
                return ResourceManager.GetString("RecursosProyectos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefonos.
        /// </summary>
        internal static string Telefonos {
            get {
                return ResourceManager.GetString("Telefonos", resourceCulture);
            }
        }
    }
}
